// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: articles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArticleByPodId = `-- name: GetArticleByPodId :one
SELECT article_text FROM articles WHERE pod_id = $1 LIMIT 1
`

func (q *Queries) GetArticleByPodId(ctx context.Context, podID pgtype.Int4) (string, error) {
	row := q.db.QueryRow(ctx, getArticleByPodId, podID)
	var article_text string
	err := row.Scan(&article_text)
	return article_text, err
}

const getArticleOwner = `-- name: GetArticleOwner :one
SELECT p.created_by FROM articles a INNER JOIN pods p ON a.pod_id = p.id WHERE a.pod_id = $1 LIMIT 1
`

func (q *Queries) GetArticleOwner(ctx context.Context, podID pgtype.Int4) (string, error) {
	row := q.db.QueryRow(ctx, getArticleOwner, podID)
	var created_by string
	err := row.Scan(&created_by)
	return created_by, err
}

const insertArticle = `-- name: InsertArticle :exec
INSERT INTO articles (pod_id, article_text)
VALUES ($1, $2)
`

type InsertArticleParams struct {
	PodID       pgtype.Int4
	ArticleText string
}

func (q *Queries) InsertArticle(ctx context.Context, arg InsertArticleParams) error {
	_, err := q.db.Exec(ctx, insertArticle, arg.PodID, arg.ArticleText)
	return err
}
