// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: articles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArticleByPodId = `-- name: GetArticleByPodId :one
SELECT article_text FROM articles WHERE pod_id = $1 LIMIT 1
`

func (q *Queries) GetArticleByPodId(ctx context.Context, podID pgtype.Int4) (string, error) {
	row := q.db.QueryRow(ctx, getArticleByPodId, podID)
	var article_text string
	err := row.Scan(&article_text)
	return article_text, err
}

const getArticlePodInfo = `-- name: GetArticlePodInfo :one
SELECT p.created_by,p.is_public FROM articles a INNER JOIN pods p ON a.pod_id = p.id WHERE a.pod_id = $1 LIMIT 1
`

type GetArticlePodInfoRow struct {
	CreatedBy string
	IsPublic  pgtype.Bool
}

func (q *Queries) GetArticlePodInfo(ctx context.Context, podID pgtype.Int4) (GetArticlePodInfoRow, error) {
	row := q.db.QueryRow(ctx, getArticlePodInfo, podID)
	var i GetArticlePodInfoRow
	err := row.Scan(&i.CreatedBy, &i.IsPublic)
	return i, err
}

const insertArticle = `-- name: InsertArticle :exec
INSERT INTO articles (pod_id, article_text)
VALUES ($1, $2)
`

type InsertArticleParams struct {
	PodID       pgtype.Int4
	ArticleText string
}

func (q *Queries) InsertArticle(ctx context.Context, arg InsertArticleParams) error {
	_, err := q.db.Exec(ctx, insertArticle, arg.PodID, arg.ArticleText)
	return err
}
