// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feedback.sql

package db

import (
	"context"
)

const insertFeedback = `-- name: InsertFeedback :exec
INSERT INTO feedbacks (created_by, feedback)
VALUES ($1, $2)
`

type InsertFeedbackParams struct {
	CreatedBy string
	Feedback  []byte
}

func (q *Queries) InsertFeedback(ctx context.Context, arg InsertFeedbackParams) error {
	_, err := q.db.Exec(ctx, insertFeedback, arg.CreatedBy, arg.Feedback)
	return err
}
