// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: jobs.sql

package db

import (
	"context"
)

const getJobStatusByID = `-- name: GetJobStatusByID :one
SELECT job_status 
FROM jobs 
WHERE id = $1
`

func (q *Queries) GetJobStatusByID(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, getJobStatusByID, id)
	var job_status int32
	err := row.Scan(&job_status)
	return job_status, err
}

const getJobStatusByPodID = `-- name: GetJobStatusByPodID :one
SELECT job_status 
FROM jobs 
WHERE pod_id = $1
`

func (q *Queries) GetJobStatusByPodID(ctx context.Context, podID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getJobStatusByPodID, podID)
	var job_status int32
	err := row.Scan(&job_status)
	return job_status, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs(pod_id)
VALUES($1)
RETURNING id
`

func (q *Queries) InsertJob(ctx context.Context, podID int32) (int32, error) {
	row := q.db.QueryRow(ctx, insertJob, podID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateJobStatusByID = `-- name: UpdateJobStatusByID :exec
UPDATE jobs
SET job_status = $2
WHERE id = $1
`

type UpdateJobStatusByIDParams struct {
	ID        int32
	JobStatus int32
}

func (q *Queries) UpdateJobStatusByID(ctx context.Context, arg UpdateJobStatusByIDParams) error {
	_, err := q.db.Exec(ctx, updateJobStatusByID, arg.ID, arg.JobStatus)
	return err
}
