// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID          int32
	PodID       pgtype.Int4
	ArticleText string
	CreatedAt   pgtype.Timestamp
	CreatedBy   string
}

type Job struct {
	ID        int32
	PodID     int32
	JobStatus int32
}

type Pod struct {
	ID        int32
	Link      string
	CreatedAt pgtype.Timestamp
}

type Question struct {
	ID            int32
	QuizzesID     pgtype.Int4
	QuestionText  string
	Options       []string
	CorrectOption int32
}

type Quiz struct {
	ID        int32
	PodID     pgtype.Int4
	CreatedAt pgtype.Timestamp
	CreatedBy string
}
