// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID          int32
	PodID       pgtype.Int4
	ArticleText string
	CreatedAt   pgtype.Timestamp
}

type Feedback struct {
	CreatedBy string
	Feedback  []byte
	CreatedAt pgtype.Timestamp
}

type Job struct {
	ID        int32
	PodID     int32
	JobStatus int32
}

type Pod struct {
	ID        int32
	Title     string
	Link      string
	CreatedAt pgtype.Timestamp
	CreatedBy string
	IsPublic  pgtype.Bool
}

type Question struct {
	ID            int32
	QuizzesID     pgtype.Int4
	QuestionText  string
	Options       []string
	CorrectOption int32
}

type Quiz struct {
	ID        int32
	PodID     pgtype.Int4
	CreatedAt pgtype.Timestamp
}

type Usage struct {
	ID      int32
	UserID  string
	Credits int32
}
