// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pods.sql

package db

import (
	"context"
)

const getPodByLink = `-- name: GetPodByLink :many
select id, link, created_at from pods where link = $1
`

func (q *Queries) GetPodByLink(ctx context.Context, link string) ([]Pod, error) {
	rows, err := q.db.Query(ctx, getPodByLink, link)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pod
	for rows.Next() {
		var i Pod
		if err := rows.Scan(&i.ID, &i.Link, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPod = `-- name: InsertPod :one
INSERT INTO pods (link)
VALUES ($1)
RETURNING id
`

func (q *Queries) InsertPod(ctx context.Context, link string) (int32, error) {
	row := q.db.QueryRow(ctx, insertPod, link)
	var id int32
	err := row.Scan(&id)
	return id, err
}
