// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pods.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPodByLink = `-- name: GetPodByLink :many
select id, title, link, created_at, created_by, is_public from pods where link = $1
`

func (q *Queries) GetPodByLink(ctx context.Context, link string) ([]Pod, error) {
	rows, err := q.db.Query(ctx, getPodByLink, link)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pod
	for rows.Next() {
		var i Pod
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Link,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.IsPublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPodOwner = `-- name: GetPodOwner :one
SELECT created_by,is_public FROM pods WHERE id = $1
`

type GetPodOwnerRow struct {
	CreatedBy string
	IsPublic  pgtype.Bool
}

func (q *Queries) GetPodOwner(ctx context.Context, id int32) (GetPodOwnerRow, error) {
	row := q.db.QueryRow(ctx, getPodOwner, id)
	var i GetPodOwnerRow
	err := row.Scan(&i.CreatedBy, &i.IsPublic)
	return i, err
}

const getPodsByUserID = `-- name: GetPodsByUserID :many
SELECT id, title, link, created_at, created_by, is_public FROM pods WHERE created_by = $1
`

func (q *Queries) GetPodsByUserID(ctx context.Context, createdBy string) ([]Pod, error) {
	rows, err := q.db.Query(ctx, getPodsByUserID, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pod
	for rows.Next() {
		var i Pod
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Link,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.IsPublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPod = `-- name: InsertPod :one
INSERT INTO pods (link,title,created_by)
VALUES ($1,$2,$3)
RETURNING id
`

type InsertPodParams struct {
	Link      string
	Title     string
	CreatedBy string
}

func (q *Queries) InsertPod(ctx context.Context, arg InsertPodParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertPod, arg.Link, arg.Title, arg.CreatedBy)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updatePodIsPublic = `-- name: UpdatePodIsPublic :exec
UPDATE pods SET is_public = $1 WHERE id = $2
`

type UpdatePodIsPublicParams struct {
	IsPublic pgtype.Bool
	ID       int32
}

func (q *Queries) UpdatePodIsPublic(ctx context.Context, arg UpdatePodIsPublicParams) error {
	_, err := q.db.Exec(ctx, updatePodIsPublic, arg.IsPublic, arg.ID)
	return err
}
