// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	GetJobStatusByID(ctx context.Context, id int32) (int32, error)
	GetJobStatusByPodID(ctx context.Context, podID int32) (int32, error)
	GetPodByLink(ctx context.Context, link string) ([]Pod, error)
	InsertArticle(ctx context.Context, arg InsertArticleParams) error
	InsertJob(ctx context.Context, podID int32) (int32, error)
	InsertPod(ctx context.Context, link string) (int32, error)
	InsertQuestion(ctx context.Context, arg InsertQuestionParams) (int32, error)
	InsertQuiz(ctx context.Context, arg InsertQuizParams) (int32, error)
	UpdateJobStatusByID(ctx context.Context, arg UpdateJobStatusByIDParams) error
}

var _ Querier = (*Queries)(nil)
