// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetArticleByPodId(ctx context.Context, podID pgtype.Int4) (string, error)
	GetArticleOwner(ctx context.Context, podID pgtype.Int4) (string, error)
	GetJobStatusByID(ctx context.Context, id int32) (int32, error)
	GetJobStatusByPodID(ctx context.Context, podID int32) (int32, error)
	GetPodByLink(ctx context.Context, link string) ([]Pod, error)
	GetPodsByUserID(ctx context.Context, createdBy string) ([]Pod, error)
	GetQuestionByQuizId(ctx context.Context, quizzesID pgtype.Int4) ([]GetQuestionByQuizIdRow, error)
	GetQuizByPodId(ctx context.Context, podID pgtype.Int4) (GetQuizByPodIdRow, error)
	GetQuizOwner(ctx context.Context, podID pgtype.Int4) (string, error)
	InsertArticle(ctx context.Context, arg InsertArticleParams) error
	InsertJob(ctx context.Context, podID int32) (int32, error)
	InsertPod(ctx context.Context, arg InsertPodParams) (int32, error)
	InsertQuestion(ctx context.Context, arg InsertQuestionParams) (int32, error)
	InsertQuiz(ctx context.Context, podID pgtype.Int4) (int32, error)
	UpdateJobStatusByID(ctx context.Context, arg UpdateJobStatusByIDParams) error
}

var _ Querier = (*Queries)(nil)
