// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: questions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getQuestionByQuizId = `-- name: GetQuestionByQuizId :many
SELECT id,question_text,options,correct_option FROM questions WHERE quizzes_id = $1
`

type GetQuestionByQuizIdRow struct {
	ID            int32
	QuestionText  string
	Options       []string
	CorrectOption int32
}

func (q *Queries) GetQuestionByQuizId(ctx context.Context, quizzesID pgtype.Int4) ([]GetQuestionByQuizIdRow, error) {
	rows, err := q.db.Query(ctx, getQuestionByQuizId, quizzesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuestionByQuizIdRow
	for rows.Next() {
		var i GetQuestionByQuizIdRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionText,
			&i.Options,
			&i.CorrectOption,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertQuestion = `-- name: InsertQuestion :one
INSERT INTO questions (quizzes_id, question_text, options, correct_option)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertQuestionParams struct {
	QuizzesID     pgtype.Int4
	QuestionText  string
	Options       []string
	CorrectOption int32
}

func (q *Queries) InsertQuestion(ctx context.Context, arg InsertQuestionParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertQuestion,
		arg.QuizzesID,
		arg.QuestionText,
		arg.Options,
		arg.CorrectOption,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
