// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: questions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertQuestion = `-- name: InsertQuestion :one
INSERT INTO questions (quizzes_id, question_text, options, correct_option)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertQuestionParams struct {
	QuizzesID     pgtype.Int4
	QuestionText  string
	Options       []string
	CorrectOption int32
}

func (q *Queries) InsertQuestion(ctx context.Context, arg InsertQuestionParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertQuestion,
		arg.QuizzesID,
		arg.QuestionText,
		arg.Options,
		arg.CorrectOption,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
