// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: quizzes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertQuiz = `-- name: InsertQuiz :one
INSERT INTO quizzes (pod_id, created_by)
VALUES ($1, $2)
RETURNING id
`

type InsertQuizParams struct {
	PodID     pgtype.Int4
	CreatedBy string
}

func (q *Queries) InsertQuiz(ctx context.Context, arg InsertQuizParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertQuiz, arg.PodID, arg.CreatedBy)
	var id int32
	err := row.Scan(&id)
	return id, err
}
