// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: quizzes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getQuizByPodId = `-- name: GetQuizByPodId :one
SELECT id,pod_id FROM quizzes WHERE pod_id = $1 LIMIT 1
`

type GetQuizByPodIdRow struct {
	ID    int32
	PodID pgtype.Int4
}

func (q *Queries) GetQuizByPodId(ctx context.Context, podID pgtype.Int4) (GetQuizByPodIdRow, error) {
	row := q.db.QueryRow(ctx, getQuizByPodId, podID)
	var i GetQuizByPodIdRow
	err := row.Scan(&i.ID, &i.PodID)
	return i, err
}

const getQuizPodInfo = `-- name: GetQuizPodInfo :one
SELECT p.created_by,p.is_public FROM quizzes q INNER JOIN pods p ON q.pod_id = p.id WHERE q.pod_id = $1 LIMIT 1
`

type GetQuizPodInfoRow struct {
	CreatedBy string
	IsPublic  pgtype.Bool
}

func (q *Queries) GetQuizPodInfo(ctx context.Context, podID pgtype.Int4) (GetQuizPodInfoRow, error) {
	row := q.db.QueryRow(ctx, getQuizPodInfo, podID)
	var i GetQuizPodInfoRow
	err := row.Scan(&i.CreatedBy, &i.IsPublic)
	return i, err
}

const insertQuiz = `-- name: InsertQuiz :one
INSERT INTO quizzes (pod_id)
VALUES ($1)
RETURNING id
`

func (q *Queries) InsertQuiz(ctx context.Context, podID pgtype.Int4) (int32, error) {
	row := q.db.QueryRow(ctx, insertQuiz, podID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
