// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: usage.sql

package db

import (
	"context"
)

const decrementCredit = `-- name: DecrementCredit :one
UPDATE usage SET credits = credits - $1 WHERE user_id = $2 RETURNING credits
`

type DecrementCreditParams struct {
	Credits int32
	UserID  string
}

func (q *Queries) DecrementCredit(ctx context.Context, arg DecrementCreditParams) (int32, error) {
	row := q.db.QueryRow(ctx, decrementCredit, arg.Credits, arg.UserID)
	var credits int32
	err := row.Scan(&credits)
	return credits, err
}

const deleteCredit = `-- name: DeleteCredit :exec
DELETE FROM usage WHERE user_id = $1
`

func (q *Queries) DeleteCredit(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteCredit, userID)
	return err
}

const getRemainingCredits = `-- name: GetRemainingCredits :one
SELECT credits from usage WHERE user_id = $1
`

func (q *Queries) GetRemainingCredits(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRow(ctx, getRemainingCredits, userID)
	var credits int32
	err := row.Scan(&credits)
	return credits, err
}

const insertCredit = `-- name: InsertCredit :exec
INSERT INTO usage (user_id, credits) VALUES ($1, $2)
`

type InsertCreditParams struct {
	UserID  string
	Credits int32
}

func (q *Queries) InsertCredit(ctx context.Context, arg InsertCreditParams) error {
	_, err := q.db.Exec(ctx, insertCredit, arg.UserID, arg.Credits)
	return err
}

const isCreditExist = `-- name: IsCreditExist :one
SELECT EXISTS(SELECT 1 FROM usage WHERE user_id = $1)
`

func (q *Queries) IsCreditExist(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, isCreditExist, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateCredit = `-- name: UpdateCredit :one
UPDATE usage SET credits = $2 WHERE user_id = $1 RETURNING credits
`

type UpdateCreditParams struct {
	UserID  string
	Credits int32
}

func (q *Queries) UpdateCredit(ctx context.Context, arg UpdateCreditParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateCredit, arg.UserID, arg.Credits)
	var credits int32
	err := row.Scan(&credits)
	return credits, err
}
